### ISSUE TITLE
Status of this repository and support for inline-datum?

### ISSUE THREAD

**Issue by ross-spencer** [cardano-foundation/cf-explorer#25]
Hi Folks - just poking around the explorer a little, it's looking great. Where's the best place to learn more about this project's status and milestones? Also, are y'all working on enabling viewing of reference-inputs/inline-datum via the UI?

**Comment by fabianbormann** [comment]
Hi @ross-spencer sorry for the delay. I didn't see the issue here. We are currently working on the next iteration of the explorer and it will come with a feature to display reference inputs. 😊 Unfortunately we are not 💯 % open source **yet**. We are currently preparing the open source launch and with it, we will open a lot of (currently) internal roadmaps and sprint scopes to the public. Thank you for your feature request and I will close this issue once we published the next explorer version!

**Comment by ross-spencer** [comment]
Awesome, thanks @fabianbormann looking forward to check it out when it's available!

**Comment by fabianbormann** [comment]
@ross-spencer we now display reference inputs / scripts within the transaction > smart contract view 😊 

https://beta.explorer.cardano.org/en/transaction/84de89c779db2c9fca7509517d7e7d665f3646e647138915a2c45947173061a6/contracts

<img width="1109" alt="image" src="https://github.com/cardano-foundation/cf-explorer/assets/1525818/3e97b2d8-b624-4a3f-b9f3-19ee4be9d45a">
